#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Sublime Text
##

module_name=sublime


gitignore "*.sublime-project"
gitignore "*.sublime-workspace"

prepare_profiled_config "packages"

sed "/###PACKAGES###/{
    r $SCRIPT_BASE_DIR/$module_name/packages
    d
}" "$SCRIPT_BASE_DIR/$module_name/subl_packages.base" > "$SCRIPT_BASE_DIR/$module_name/Package Control.sublime-settings"


# TODO: on a fresh install it might be `~/.config/sublime-text`??
if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	SUBL_ROOT="$HOME/Library/Application Support/Sublime Text 3"
	SUBL_CONFIG="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
	FONT_SIZE=18
elif [[ "${DOTFILES_OS:-}" == "Linux" ]]; then
	SUBL_ROOT="$HOME/.config/sublime-text-3"
	SUBL_CONFIG="$HOME/.config/sublime-text-3/Packages/User"
	FONT_SIZE=14
else
	errorprint "Needs \$DOTFILES_OS set"
	exit 1
fi


if [ ! -f "$SUBL_ROOT/Installed Packages/Package Control.sublime-package" ]; then
	infoprint "[$module_name] installing Package Control"
	# using `command` to avoid the hack for Wayland...
	command subl --command "install_package_control"

	# NOTE: Mac might need this after installing: https://github.com/wbond/package_control/issues/1612
fi


# https://github.com/sublimehq/sublime_text/issues/32

sed "s/###FONT_SIZE###/${FONT_SIZE}/" "$SCRIPT_BASE_DIR/$module_name/subl_settings.base" > "$SCRIPT_BASE_DIR/$module_name/Preferences.sublime-settings"



infoprint "[$module_name] creating dotfiles symlinks..."
# Settings (general)
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default (Linux).sublime-keymap" "$SUBL_CONFIG/Default (Linux).sublime-keymap" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default (OSX).sublime-keymap" "$SUBL_CONFIG/Default (OSX).sublime-keymap" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Preferences.sublime-settings" "$SUBL_CONFIG/Preferences.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Package Control.sublime-settings" "$SUBL_CONFIG/Package Control.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/custom.sublime-color-scheme" "$SUBL_CONFIG/custom.sublime-color-scheme" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/LSP.sublime-settings" "$SUBL_CONFIG/LSP.sublime-settings" 1> /dev/null

# Settings (language-specific)
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Ruby.sublime-settings" "$SUBL_CONFIG/Ruby.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Elixir.sublime-settings" "$SUBL_CONFIG/Elixir.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Git Commit.sublime-settings" "$SUBL_CONFIG/Git Commit.sublime-settings" 1> /dev/null

# Completions / snippets
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/ruby.sublime-completions" "$SUBL_CONFIG/ruby.sublime-completions" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/ipdb.sublime-snippet" "$SUBL_CONFIG/ipdb.sublime-snippet" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/lorem.sublime-snippet" "$SUBL_CONFIG/lorem.sublime-snippet" 1> /dev/null

# Syntaxes
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/RSpec.sublime-syntax" "$SUBL_CONFIG/RSpec.sublime-syntax" 1> /dev/null

# Commands
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default.sublime-commands" "$SUBL_CONFIG/Default.sublime-commands" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/AssignRailsSyntax.py" "$SUBL_CONFIG/AssignRailsSyntax.py" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/AssignRSpecSyntax.py" "$SUBL_CONFIG/AssignRSpecSyntax.py" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/NewProjectFromRootCommand.py" "$SUBL_CONFIG/NewProjectFromRootCommand.py" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/ProjectInStatusbar.py" "$SUBL_CONFIG/ProjectInStatusbar.py" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/SingleLastSelectionCommand.py" "$SUBL_CONFIG/SingleLastSelectionCommand.py" 1> /dev/null
