#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Sublime Text
##

module_name=sublime


gitignore "*.sublime-project"
gitignore "*.sublime-workspace"

prepare_profiled_config "packages"
sed "/###PACKAGES###/{
    r $SCRIPT_BASE_DIR/$module_name/packages
    d
}" "$SCRIPT_BASE_DIR/$module_name/subl_packages.base" > "$SCRIPT_BASE_DIR/$module_name/Package Control.sublime-settings"
remove_profiled_config "packages"


if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	SUBL_ROOT="$HOME/Library/Application Support/Sublime Text"
	SUBL_CONFIG="$HOME/Library/Application Support/Sublime Text/Packages/User"
	FONT_SIZE=18
elif [[ "${DOTFILES_OS:-}" == "Linux" ]]; then
	SUBL_ROOT="$HOME/.config/sublime-text"
	SUBL_CONFIG="$HOME/.config/sublime-text/Packages/User"
	FONT_SIZE=14
else
	errorprint "Needs \$DOTFILES_OS set"
	exit 1
fi


if [ ! -f "$SUBL_ROOT/Installed Packages/Package Control.sublime-package" ]; then
	infoprint "[$module_name] installing Package Control"
	if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
		# https://github.com/wbond/package_control/issues/1612
		# NOTE: Fixed in ST > 4200?
		curl -s https://api.github.com/repos/sublimehq/package_control/releases/latest \
			| jq -r '.assets[0].browser_download_url'\
			| xargs curl -sL -o "$SUBL_ROOT/Installed Packages/Package Control.sublime-package"
	elif [[ "${DOTFILES_OS:-}" == "Linux" ]]; then
		subl --command "install_package_control"
	fi
fi


# https://github.com/sublimehq/sublime_text/issues/32

sed "s/###FONT_SIZE###/${FONT_SIZE}/" "$SCRIPT_BASE_DIR/$module_name/subl_settings.base" > "$SCRIPT_BASE_DIR/$module_name/Preferences.sublime-settings"



infoprint "[$module_name] creating dotfiles symlinks..."
# Settings (general)
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default (Linux).sublime-keymap" "$SUBL_CONFIG/Default (Linux).sublime-keymap" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default (OSX).sublime-keymap" "$SUBL_CONFIG/Default (OSX).sublime-keymap" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Preferences.sublime-settings" "$SUBL_CONFIG/Preferences.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Package Control.sublime-settings" "$SUBL_CONFIG/Package Control.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/custom.sublime-color-scheme" "$SUBL_CONFIG/custom.sublime-color-scheme" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/Default.sublime-commands" "$SUBL_CONFIG/Default.sublime-commands" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/LSP.sublime-settings" "$SUBL_CONFIG/LSP.sublime-settings" 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/LSP-copilot.sublime-settings" "$SUBL_CONFIG/LSP-copilot.sublime-settings" 1> /dev/null

ln -sf "${SCRIPT_BASE_DIR}/$module_name/LangSettings/"* "$SUBL_CONFIG"
ln -sf "${SCRIPT_BASE_DIR}/$module_name/Completions/"* "$SUBL_CONFIG"
ln -sf "${SCRIPT_BASE_DIR}/$module_name/Syntaxes/"* "$SUBL_CONFIG"
ln -sf "${SCRIPT_BASE_DIR}/$module_name/Plugins/"* "$SUBL_CONFIG"
