#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Sway
##

module_name=sway


# Linux only
if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	exit
fi


mkdir -p ~/.config/sway

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/config" ~/.config/sway/config 1> /dev/null
