#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Ruby
##

module_name=ruby

infoprint "[$module_name] making gems install without docs"
add_if_not_there 'gem: --no-document' ~/.gemrc

infoprint "[$module_name] installing latest ruby"
mise use --global ruby@latest

infoprint "[$module_name] installing default gems..."
mise use --global gem:rubocop
mise use --global gem:ruby-lsp
if is_personal_or_hybrid; then
	mise use --global gem:download_tv
fi

##
# Symlinks
##
mkdir -p "$XDG_CONFIG_HOME/irb"
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/irbrc" "$XDG_CONFIG_HOME/irb/irbrc" 1> /dev/null
