#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Ghostty
##

module_name=ghostty


infoprint "[$module_name] enabling systemd service..."
command_exists systemctl && systemctl enable --user app-com.mitchellh.ghostty.service

# Need it here and not (just) on hyprland as systemd
# wins the race sometimes and ghostty runs without the env var
# https://github.com/ghostty-org/ghostty/discussions/8899
mkdir -p ~/.config/environment.d/
add_if_not_there "GTK_IM_MODULE=simple" ~/.config/environment.d/10-gtk-im.conf

mkdir -p ~/.config/ghostty

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/config" ~/.config/ghostty/config 1> /dev/null
if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	ln -sfv "${SCRIPT_BASE_DIR}/$module_name/config-macos" ~/.config/ghostty/config-macos 1> /dev/null
else
	ln -sfv "${SCRIPT_BASE_DIR}/$module_name/config-linux" ~/.config/ghostty/config-linux 1> /dev/null
fi
