#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Git
##

module_name=git


if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	gitignore ".DS_Store"
fi

infoprint "[$module_name] creating dotfiles symlinks..."
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig" ~/.gitconfig 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-personal.gitconfig" ~/.gitconfig-personal 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-work.gitconfig" ~/.gitconfig-work 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-delta.gitconfig" ~/.gitconfig-delta 1> /dev/null
