#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Git
##

module_name=git


if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	gitignore ".DS_Store"
fi
gitignore "*.local"
gitignore "*.local.md"

if [[ ! -f ~/.gitconfig.local ]]; then
	touch ~/.gitconfig.local
	# set default credentials for all paths by default
	if is_personal || is_work; then
		printf '[include]\n' > ~/.gitconfig.local
		printf '\tpath = ~/.gitconfig-%s\n' "$DOTFILES_PROFILE" >> ~/.gitconfig.local
	fi
fi

infoprint "[$module_name] creating dotfiles symlinks..."
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig" ~/.gitconfig 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-personal.gitconfig" ~/.gitconfig-personal 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-work.gitconfig" ~/.gitconfig-work 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitconfig-delta.gitconfig" ~/.gitconfig-delta 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/gitmessage" ~/.gitmessage 1> /dev/null
