set number
set incsearch
set ignorecase smartcase
set autoindent
" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start
set ruler       " show the cursor position all the time
set showcmd     " display incomplete commands
set wildmenu        " display completion matches in a status line
set cursorline
" If a file is changed outside of vim, automatically reload it without asking
set autoread

syntax on
filetype plugin indent on

set termguicolors
let g:rehash256 = 1
colorscheme molokai
