# Apt-get
alias sagi='sudo apt-get install'
alias sagu='sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y'
alias sagc='sudo apt-get autoremove && sudo apt-get purge && sudo apt-get clean && sudo apt-get autoclean && sudo apt-get check'

# Pacman
alias paci='sudo pacman -S'
alias pacu='sudo pacman -Syu'

# Terminal
alias ls='ls -F --color=auto'
alias la='ls -AF --color=auto'
alias ll='ls -AoF --color=auto'
alias grep='grep --color=auto'
alias df='df -h'
alias cls='clear'
alias calc='bc -q -l'

# App shortcuts
alias g='google-chrome-stable'
alias subl='subl3'

# Misc
alias snast='sudo nast -i wlan1 -m'
alias ubuntu-files=' dpkg --get-selections | grep -v deinstall > apps && subl -w apps'
alias starwars='telnet towel.blinkenlights.nl'

# Media functions
#alias twitch='livestream'
alias music='play_music'
alias hdmi='xrandr --output HDMI-1 --auto --same-as eDP-1'
alias tv='~/projects/daily-shows/bin/run'
alias dl='~/projects/daily-shows/bin/dl'

command_exists() {
    type "$1" &> /dev/null ;
}

# Exiting
alias q='exit'
alias bye='sudo shutdown -t 0'

#livestream() {
#  livestreamer twitch.tv/$1 $2||best
#}

play_music() {
	mpd
	ncmpcpp && mpd --kill
}