# Pacman
alias paci='sudo pacman -S'
alias pacu='sudo pacman -Syu'
alias pacuw='sudo pacman -Syuw'
alias pacc='paccache -rk 1 && paccache -ruk0 && sudo pacman -Rns $(pacman -Qtdq)'

# Terminal
alias ls='ls -F --color=auto'
alias la='ls -AF --color=auto'
alias ll='ls -AoFh --color=auto'
alias top='htop'
alias diff='diff -wu'
alias pgrep='pgrep -l'
alias grep='grep -n --color=auto'
alias rg='rg -n'
alias df='df -h'
alias du='du -h'
alias cls='clear'
alias calc='bc -q -l'

# Notifications
alias dnd='notify-send "DUNST_COMMAND_PAUSE"'
alias dnd-='notify-send "DUNST_COMMAND_RESUME"'

# App shortcuts
alias g='chromium --process-per-site'
alias subl='subl3'

# Misc
alias snast='sudo nast -i wlan1 -m'
alias starwars='telnet towel.blinkenlights.nl'

# Media functions
alias music='play_music'
alias hdmi='xrandr --output HDMI-1 --auto --same-as eDP-1'
alias rn='~/projects/tvutils/bin/rename .'
alias tvmove='~/projects/tvutils/bin/tvmove ~/Downloads ~/Series'
alias dl='tv -d'

command_exists() {
    type "$1" &> /dev/null ;
}

# Exiting
alias q='exit'
alias bye='sudo shutdown -t 0'

play_music() {
	mpd
	ncmpcpp && mpd --kill
}