# Pacman
alias paci='sudo pacman -S'
alias pacu='sudo pacman -Syu'
alias pacuw='sudo pacman -Syuw'
alias pacc='paccache -rk 1 && paccache -ruk0 && sudo pacman -Rns $(pacman -Qtdq)'

# Terminal
alias ls='ls -F --color=auto'
alias la='ls -AF --color=auto'
alias ll='ls -AoFh --color=auto'
alias diff='diff -wu'
alias pgrep='pgrep -l'
alias grep='grep -n --color=auto'
alias rg='rg -n --smart-case'
alias df='df -h'
alias du='du -h'
alias cls='clear'
alias calc='bc -q -l'
alias cal='cal --monday'
alias vim='nvim'
if [[ -x `which htop` ]]; then alias top="htop"; fi

# Log in as postgres
alias pg='sudo -u postgres -i'

# Notifications
alias dnd='notify-send "DUNST_COMMAND_PAUSE"'
alias dnd-='notify-send "DUNST_COMMAND_RESUME"'

# Media functions
alias music='play_music'
alias hdmi='xrandr --output HDMI-1 --auto --right-of eDP-1'
alias rn='~/projects/tvrename/bin/rename'

# Helpful functions
# fuzzy cd
function cdf() { cd $1*/ }
# removes returns for "grep" on greps of ps output
function pps() { ps aux | grep "$@" | grep -v "grep"; }
# kills all processes returned by `pps`
function ppsk() { pps $@ | awk '{print $2}' | xargs kill -9; }
function cpcd() { cp $1 $2 && cd $2; }
function mvcd() { mv $1 $2 && cd $2; }

command_exists() {
    type "$1" &> /dev/null ;
}

play_music() {
	mpd
	ncmpcpp && mpd --kill
}

csh() {
	\curl http://cheat.sh/$1
}

# Exiting
alias q='exit'
alias bye='sudo shutdown -t 0'
