#!/usr/bin/env bash

COLOR='\033[0;32m'
NC='\033[0m' # No Color

command_exists () {
	type "$1" &> /dev/null ;
}

infoprint () {
	echo -e "${COLOR}${1}${NC}"
}

aur_dl () {
	\curl -L -O "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz"
}

# Select the right install command and update system
INSTALL="sudo pacman -S --needed --noconfirm --noprogressbar"
infoprint "Updating system"
sudo pacman -Syuq --noconfirm

# Install zsh and set it as default shell
if command_exists zsh; then
	infoprint "zsh already installed"
else
	$INSTALL zsh
	chsh -s /bin/zsh
fi

infoprint "Installing programs from source/apps"
xargs -a <(cat sources/apps | \grep -v '^#') $INSTALL

# RUBY
if command_exists rvm; then
	infoprint "rvm already installed"
	infoprint "updating rvm..."
	rvm get head 1> /dev/null
	gem update -q
else
	infoprint "Installing rvm"
	\curl -sSL https://get.rvm.io | bash -s head
	source ~/.rvm/scripts/rvm
	rvm install ruby-head
	#rvm install jruby-head
	rvm use --default ruby-head
	infoprint "Installing gems"
	xargs -a <(cat sources/gems) gem install
fi

# PYTHON
infoprint "Installing pip packages"
xargs -a <(cat sources/pip) pip install --user -qq

# ELIXIR
# mix local.hex
# mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

# MPD and NCMPCPP
mkdir -p ~/.mpd/lyrics
mkdir -p ~/.mpd/playlists
mkdir -p ~/.ncmpcpp
touch ~/.mpd/mpd.log
touch ~/.mpd/tag_cache
touch ~/.mpd/mpdstate
touch ~/.mpd/mpd.pid
touch ~/.mpd/sticker.sql

# Install pacaur
if command_exists pacaur; then
	infoprint "pacaur already installed"
else
	mkdir temp
	cd temp
	aur_dl cower
	aur_dl pacaur
	tar -xvf cower*
	tar -xvf pacaur*
	cd cower
	makepkg -sri --skippgpcheck
	cd ../pacaur
	makepkg -sri
	cd ../..
	rm -rf temp
fi

# Install AUR packages
xargs -a <(cat sources/aur | \grep -v '^#') pacaur -S --needed --noconfirm --noprogressbar

infoprint "setting spanish keyboard"
localectl set-x11-keymap es

infoprint "creating symbolic links..."
source links

# Create to-do list
infoprint "creating a to-do file with more possible configurations..."

echo "* Gtk themes with lxappearance" >> todo
echo "* Install package control for Sublime" >> todo
echo "   * Install Agila" >> todo
echo "   * Install AllAutoComplete" >> todo
echo "   * Install BracketHighlighter" >> todo
echo "   * Install Elixir" >> todo
echo "   * Install Crystal" >> todo
echo "   * Install SublimeLinter, -contrib-elixirc, -ruby" >> todo
