#!/usr/bin/env bash

set -e

# Exported so the module install scripts have a ref to the base
export SCRIPT_BASE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_BASE_DIR/common" || exit 1

populate_os_zvars() {
	os="$(uname -s)"

	case "$os" in
	Linux*)
		echo "export DOTFILES_OS=Linux" > "$SCRIPT_BASE_DIR/dots/zvars"
		;;
	Darwin*)
		echo "export DOTFILES_OS=OSX" > "$SCRIPT_BASE_DIR/dots/zvars"
		;;
	*)
		errorprint "Unsupported OS: $os"
		exit 1
		;;
	esac
}

populate_profile_zvars() {
	choices=("personal" "work" "hybrid")

	if command_exists fzf; then
		profile=$(printf "%s\n" "${choices[@]}" | fzf --prompt="Select profile: ")
	else
		echo "Select profile:"
		select opt in "${choices[@]}"; do
			if [[ -n "$opt" ]]; then
				profile="$opt"
				break
			fi
		done
	fi

	# If user aborted, bail
	if [[ -z "${profile:-}" ]]; then
		errorprint "No profile selected."
		exit 1
	fi

	echo "export DOTFILES_PROFILE=$profile" >> "$SCRIPT_BASE_DIR/dots/zvars"
}

populate_os_zvars
populate_profile_zvars

source "$SCRIPT_BASE_DIR/dots/zvars"
infoprint "[main] configured & loaded zvars"

# System module - general setup & packages
infoprint "[system] installing..."
bash "$SCRIPT_BASE_DIR/system/__install"
infoprint "[main] system done"


modules_to_install=(
	zsh
	mise
	ruby
	mpd
	git
	sublime
	ghostty
	sway
	waybar
	mpv
	thunar
	nvim
	rofi
	dunst
	tailscale
)

for module in "${modules_to_install[@]}"; do
	infoprint "[$module] installing..."
	bash "$SCRIPT_BASE_DIR/$module/__install"
	infoprint "[main] $module done"
done


infoprint "[main] creating symlinks for mybin folder..."
ln -sfv ${SCRIPT_BASE_DIR}/mybin/ ~/mybin 1> /dev/null

infoprint "[main] done"
