#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Set up mise-en-place
##

module_name=mise

if command_exists mise; then
	infoprint "[$module_name] upgrading mise tools"
	mise upgrade
fi


infoprint "[$module_name] setting up mise's autocompletion"
mise use --global usage

if [ ! -d /usr/local/share/zsh ]; then
	errorprint "Can't find /usr/local/share/zsh, find another \$fpath. See https://mise.jdx.dev/installing-mise.html#autocompletion"
	exit 1
fi

if [ ! -f /usr/local/share/zsh/site-functions/_mise ]; then
	sudo chown -R "$(whoami)":"$(id -gn)" /usr/local/share/zsh
	mkdir -p /usr/local/share/zsh/site-functions
fi
# Always regenerate completions
mise completion zsh  > /usr/local/share/zsh/site-functions/_mise

infoprint "[$module_name] mise config flags"
mise settings set experimental true

gitignore "mise.local.toml"

infoprint "[$module_name] installing global mise tools"
mise use -g helm-ls@latest

infoprint "[$module_name] pruning outdated mise tools"
mise prune
