#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Set up mise-en-place
##

module_name=mise


manual_install_mise () {
	INSTALLER=$(mktemp /tmp/mise-install.XXXXXX.sh)

	echo "Fetching installer from https://mise.run ..."
	curl -fsSL https://mise.run -o "$INSTALLER"

	bat "$INSTALLER"

	printf "Proceed with installation? [y/N] "
	read -r answer
	case "$answer" in
	  [yY]|[yY][eE][sS])
	    sh "$INSTALLER"
	    ;;
	  *)
	    echo "Aborted."
	    exit 1
	    ;;
	esac
	rm -f "$INSTALLER"
}

if [[ "$DOTFILES_DISTRO" == "Arch" ]]; then
	command_exists mise || manual_install_mise
fi


gitignore "mise.local.toml"

infoprint "[$module_name] mise config flags"
mise settings set experimental true
mise settings set status.show_deps_stale false
mise settings set minimum_release_age "7d"

if command_exists mise; then
	infoprint "[$module_name] upgrading mise tools"
	mise upgrade
fi

infoprint "[$module_name] setting up usage"
mise use --global usage

infoprint "[$module_name] installing global mise tools"
mise use -g helm-ls@latest

if [[ "$DOTFILES_DISTRO" == "Fedora" ]]; then
	# we get these thru pacman in Arch
	mise use --global eza@latest
	mise use --global opencode@latest
	mise use --global typst@latest
	mise use --global kubectl@latest
	mise use --global kubectx@latest
	mise use --global kubens@latest
	mise use --global github:atanunq/viu
	mise use --global protoc@34
fi

infoprint "[$module_name] pruning outdated mise tools"
mise prune

infoprint "[$module_name] activating for this session"
eval "$(mise activate bash)"
