[tools]
"github:atanunq/viu"      = "latest"
"github:dandavison/delta" = "latest"
"github:guille/orbit"     = { version = "latest", minimum_release_age = "0d" }
"github:neovim/neovim"    = "latest"
"pipx:magic-wormhole"     = "latest"
"pipx:pgcli"              = "latest"
sops                      = "latest"
usage                     = "latest"
uv                        = "latest"

[tasks.pgcli]
run = "pgcli postgresql://postgres@localhost"

[tasks."trackr:migrate"]
run = "podman exec trackr /app/bin/migrate"

[tasks.pull-restart]
usage = 'arg "<container>"'
run   = "podman pull ghcr.io/guille/${usage_container?} && systemctl --user restart ${usage_container?}"

[tasks.feeds-db]
run = """
sqlite3 -readonly "$(podman volume inspect systemd-feeds-data | jq -r '.[0].Mountpoint + "/feeds.db"')"
"""

[tasks.upnext-db]
run = """
sqlite -readonly "$(podman volume inspect systemd-upnext-data | jq -r '.[0].Mountpoint + "/upnext.db"')"
"""

[settings]
minimum_release_age = "7d"

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = "create|source"
