#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# rofi
##

module_name=rofi


# Linux only
if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	exit
fi


infoprint "[$module_name] creating dotfiles symlinks..."
# Avoids nested symlinks
[ -e ~/.config/rofi ] && rm -rf ~/.config/rofi
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/config/" ~/.config/rofi 1> /dev/null
