#!/usr/bin/env bash

set -e

source "$SCRIPT_BASE_DIR/common"

##
# nvim
##

module_name=nvim


mkdir -p ~/.config/nvim/lua

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/init.lua" ~/.config/nvim/init.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/monokai.lua" ~/.config/nvim/lua/monokai.lua 1> /dev/null
