#!/usr/bin/env bash

set -e

source "$SCRIPT_BASE_DIR/common"

##
# nvim
##

module_name=nvim


mkdir -p ~/.config/nvim/colors

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/vimrc" ~/.config/nvim/init.vim 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/vimcolor" ~/.config/nvim/colors/molokai.vim 1> /dev/null
