#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# nvim
##

module_name=nvim


mkdir -p ~/.config/nvim/lua

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/init.lua" ~/.config/nvim/init.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/autocmds.lua" ~/.config/nvim/lua/autocmds.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/fzf.lua" ~/.config/nvim/lua/fzf.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/keybinds.lua" ~/.config/nvim/lua/keybinds.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/options.lua" ~/.config/nvim/lua/options.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/statusline.lua" ~/.config/nvim/lua/statusline.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/monokai.lua" ~/.config/nvim/lua/monokai.lua 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/lsp.lua" ~/.config/nvim/lua/lsp.lua 1> /dev/null
