
" KEYBOARD SHORTCUTS
let mapleader=","
" Leader twice to switch open files
nnoremap <leader><leader> <c-^>
" leader + Space clears search highlight
nnoremap <silent> <leader><Space> :nohlsearch<CR>
" leader + W strips all trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>
" leader + v to select text that was just pasted
nnoremap <leader>v V`]
" Leader + o to open new vertical split and switch to it
nnoremap <leader>o <C-w>v<C-w>l
" Leader + s to start replace command
nmap <Leader>s :%s//<Left>
" Leader + e to start :e in the open file's directory
cnoremap <expr> %% expand('%:h').'/'
map <leader>e :edit %%
" Move up/down by visual lines, not file lines
nnoremap j gj
nnoremap k gk
" Easier moving around splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"""""""""""""
" MULTIPURPOSE TAB KEY
" Indent if we're at the beginning of a line. Else, do completion.
"""""""""""""
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <expr> <tab> InsertTabWrapper()
inoremap <s-tab> <c-n>
nmap <tab> %

" Appearance
:set statusline=%<%f\ (%{&ft})\ %-4(%m%)%=%-19(%3l,%02c%03V%)
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
