#!/usr/bin/env bash

set -e

source "$SCRIPT_BASE_DIR/common"

##
# mpv
##

module_name=mpv


mkdir -p ~/.config/mpv

infoprint "[$module_name] creating dotfiles symlinks..."

ln -sfv "${SCRIPT_BASE_DIR}/$module_name/mpv.conf" ~/.config/mpv/mpv.conf 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/input.conf" ~/.config/mpv/input.conf 1> /dev/null
