#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# node
##

module_name=node


##
# Symlinks
##
infoprint "[$module_name] creating dotfiles symlinks..."
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/default-npm-packages" ~/.default-npm-packages 1> /dev/null


mise use -g node@latest
