#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# node
##

module_name=node


add_if_not_there "ignore-scripts=true" "$HOME/.npmrc"


mise use -g node@latest

infoprint "[$module_name] installing packages..."
mise use -g npm:dockerfile-language-server-nodejs
mise use -g npm:typescript
mise use -g npm:typescript-language-server
mise use -g npm:yaml-language-server

if is_personal_or_hybrid; then
	mise use -g npm:svelte-language-server
fi
if is_work_or_hybrid; then
	mise use -g npm:@bufbuild/buf
	mise use -g npm:graphql-language-service-cli
fi
