#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Set up restic
##

module_name=restic


# Linux only, personal only
if [[ "${DOTFILES_OS:-}" == "OSX" ]] || is_work; then
	exit
fi

# Always regenerate completions
infoprint "[$module_name] setting up restic's autocompletion"
restic generate --zsh-completion /usr/local/share/zsh/site-functions/_restic
