#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# golang
##

module_name=go


gitignore "go.work"


mise use --global go@latest
mise x -- go telemetry off

infoprint "[$module_name] installing packages..."
mise use --global go:github.com/go-delve/delve/cmd/dlv@latest
mise use --global go:golang.org/x/tools/gopls@latest
mise use --global go:golang.org/x/vuln/cmd/govulncheck@latest
mise use --global go:honnef.co/go/tools/cmd/staticcheck@latest

if is_work_or_hybrid; then
	mise use --global go:oras.land/oras/cmd/oras@latest
	mise use --global go:google.golang.org/protobuf/cmd/protoc-gen-go@latest
	mise use --global go:google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
fi
