#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# hyprland
##

module_name=hyprland


# Linux only
if [[ "${DOTFILES_OS:-}" == "OSX" ]]; then
	exit
fi


mkdir -p ~/.config/hypr/hyprland

infoprint "[$module_name] creating dotfiles symlinks... (hyprland)"
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/hyprland.lua" ~/.config/hypr/hyprland.lua 1> /dev/null

touch "${SCRIPT_BASE_DIR}/$module_name/local_confs.lua"
ln -sf "${SCRIPT_BASE_DIR}/$module_name/hyprland/"* ~/.config/hypr/hyprland/

infoprint "[$module_name] creating dotfiles symlinks... (ecosystem)"
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/hyprlock.conf" ~/.config/hypr/hyprlock.conf 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/hypridle.conf" ~/.config/hypr/hypridle.conf 1> /dev/null
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/xdph.conf" ~/.config/hypr/xdph.conf 1> /dev/null
