# See https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

# `pango-list` for font names
$font = Atkinson Hyperlegible Next

general {
    hide_cursor = false
    ignore_empty_input = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 1000 # in milliseconds
    }
}

animations {
    enabled = true

    bezier = softEase, 0.22, 1, 0.36, 1
    bezier = calmEase, 0.25, 0.1, 0.25, 1

    animation = fadeIn, 1, 8, softEase
    animation = fadeOut, 1, 6, calmEase
    animation = inputFieldDots, 1, 4, softEase
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

label {
    monitor =
    text = $TIME
    color = rgba(f5f5f4ee)
    font_size = 72
    font_family = $font
    halign = center
    valign = center
    position = 0, 155
}

input-field {
    monitor =
    size = 360, 58
    outline_thickness = 2

    inner_color = rgba(1c1917aa)
    outer_color = rgba(fbbf24ff) rgba(f97316ff) 35deg
    check_color = rgba(84cc16ff) rgba(eab308ff) 45deg
    fail_color = rgba(ef4444ff) rgba(f97316ff) 45deg

    font_color = rgba(f5f5f4ff)
    fade_on_empty = false
    rounding = 18

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.28
    dots_center = true

    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    font_family = $font
    font_size = 15
    text = $FPRINTPROMPT
    halign = center
    valign = center
    position = 0, 25
    color = rgba(e7e5e4cc)
}
