#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# python
##

module_name=python


mise settings add python.uv_venv_auto true
mise settings set pipx.uvx true


mise use --global python@latest

infoprint "[$module_name] installing Python tools with uv"
# uv and ruff are installed from system packages
mise use -g pipx:basedpyright
mise use -g pipx:dmn-pty
mise use -g pipx:pgcli
mise use -g pipx:mycli
mise use -g pipx:syntaqlite
mise use -g pipx:tombi
mise use -g pipx:ty

# install some common libs to mise's python
mise x -- uv pip install --system requests lxml

if [[ "$DOTFILES_DISTRO" == "Fedora" ]]; then
	mise use -g pipx:magic-wormhole
fi
