#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# Installs zsh plugins and symlinks the config(s)
##

module_name=zsh

##
# zsh plugins
##

git submodule update --init

[ -L ~/.powerlevel10k ] && unlink ~/.powerlevel10k
infoprint "[$module_name] linking powerlevel10k..."
ln -sf "${SCRIPT_BASE_DIR}/$module_name/powerlevel10k" ~/.powerlevel10k

[ -L ~/.fzf-tab ] && unlink ~/.fzf-tab
infoprint "[$module_name] linking fzf-tab..."
ln -sf "${SCRIPT_BASE_DIR}/$module_name/fzf-tab" ~/.fzf-tab


##
# symlinks
##

infoprint "[$module_name] creating dotfiles symlinks..."

h=$(hostname)

[[ -f "${SCRIPT_BASE_DIR}/$module_name/zshrc.$h.zsh" ]] && ln -sf "${SCRIPT_BASE_DIR}/$module_name/zshrc.$h.zsh" ~/.zshrc."$h"
[[ -f "${SCRIPT_BASE_DIR}/$module_name/zshenv.$h.zsh" ]] && ln -sf "${SCRIPT_BASE_DIR}/$module_name/zshenv.$h.zsh" ~/.zshenv."$h"

ln -sf "${SCRIPT_BASE_DIR}/$module_name/zaliases.zsh" ~/.zaliases
ln -sf "${SCRIPT_BASE_DIR}/$module_name/zkeys.zsh" ~/.zkeys
ln -sf "${SCRIPT_BASE_DIR}/$module_name/zprofile.zsh" ~/.zprofile
ln -sf "${SCRIPT_BASE_DIR}/$module_name/zshenv.zsh" ~/.zshenv
ln -sf "${SCRIPT_BASE_DIR}/$module_name/zshrc.zsh" ~/.zshrc

ln -sf "${SCRIPT_BASE_DIR}/$module_name/zvars" ~/.zvars

ln -sf "${SCRIPT_BASE_DIR}/$module_name/p10k.zsh" ~/.p10k.zsh
ln -sf "${SCRIPT_BASE_DIR}/$module_name/p10k.mise.zsh" ~/.p10k.mise.zsh

ln -sf "${SCRIPT_BASE_DIR}/$module_name/zsh-history-substring-search.zsh" ~/.zhist_substr
