# For Sublime Text
eval "$(mise activate zsh --shims)"

export XDG_CONFIG_HOME="$HOME/.config"

if [ -z "$WAYLAND_DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ] ; then
    export ELECTRON_OZONE_PLATFORM_HINT=wayland # run electron apps in wayland mode
    exec sway
fi
