#!/usr/bin/env bash

# only lock on work machines
if [[ "$DOTFILES_PROFILE" == "work" || "$DOTFILES_PROFILE" == "hybrid" ]]; then
	mpc pause >/dev/null || true
	# avoid starting multiple hyprlock instances.
	pidof hyprlock || hyprlock
fi
