#!/usr/bin/env bash
# shellcheck disable=SC1091

set -e

source "$SCRIPT_BASE_DIR/common"

##
# fd
##

module_name=fd

if command_exists fdfind; then
	mkdir -p ~/.local/bin
	ln -s "$(command -v fdfind)" ~/.local/bin/fd
fi

mkdir -p ~/.config/fd

infoprint "[$module_name] creating dotfiles symlinks..."
ln -sfv "${SCRIPT_BASE_DIR}/$module_name/fdignore" ~/.config/fd/ignore 1> /dev/null
